// <auto-generated />
namespace PIS_Lab4.Migrations.PhoneBooks
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Droppedtableandstartedfrombegining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Droppedtableandstartedfrombegining));
        
        string IMigrationMetadata.Id
        {
            get { return "202302221507037_Dropped table and started from begining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
